# Generated by Django 3.2.6 on 2021-08-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ManyToManyField(to='users.Rol'),
        ),
    ]
