# Generated by Django 3.2.6 on 2021-08-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ManyToManyField(default='USER_CLIENT', to='users.Rol'),
        ),
    ]
