# Generated by Django 3.2.6 on 2021-09-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='username', max_length=50, verbose_name='auth provider'),
        ),
    ]
